# Default foreground and background colors for setterm
# These should be one of: black, red, green, yellow, blue, magenta, cyan, white
foreground = "base05"
background = "base00"

color0 = "282936" #background
color1 = "3a3c4e"
color2 = "4d4f68"
color3 = "626483"
color4 = "62d6e8"
color5 = "e9e9f4" #foreground
color6 = "f1f2f8"
color7 = "f7f7fb"
color8 = "ea51b2"
color9 = "b45bcf"
color10 = "00f769"
color11 = "ebff87"
color12 = "a1efe4"
color13 = "62d6e8"
color14 = "b45bcf"
color15 = "00f769"
